# Linear Algebra Recollection

## Vector Operations

In [1]:
import numpy as np

In [4]:
u = np.array([2,4,6,8])
v = np.array([3,5,7,9])

In [5]:
# Addition
u + v

array([ 5,  9, 13, 17])

In [6]:
# Subtraction
u - v

array([-1, -1, -1, -1])

In [7]:
# Multiplication
u * v

array([ 6, 20, 42, 72])

In [8]:
# Scalar Multiplication
v * 2

array([ 6, 10, 14, 18])

#### Vector Vector Multiplication   

In [9]:
def vec_vec_multiplication(a, b):
    assert a.shape[0] == b.shape[0]
    n = a.shape[0]
    result = 0.0

    for i in range(n):
        result = result + a[i] * b[i]   # summation of i=0 to n-1 (ui*vi)
    return result


In [10]:
vec_vec_multiplication(u,v)

140.0

In [11]:
u.dot(v)

140

#### Matrix Vector Multiplication

In [15]:
mat_a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
vec_b = np.array([1,2,3])

In [17]:
mat_a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [16]:
mat_a.shape         #mat_a[0] = rows #mat_a[1] = columns

(4, 3)

In [26]:
def mat_vec_multiplication(mat, vec):
    assert mat.shape[1] == vec.shape[0]

    result = np.zeros((mat.shape[0]))
    for i in range(mat.shape[0]):
        result[i] = vec_vec_multiplication(mat[i], vec)
    return result

In [27]:
mat_vec_multiplication(mat_a, vec_b)

array([14., 32., 50., 68.])

In [28]:
mat_a.dot(vec_b)

array([14, 32, 50, 68])

#### Matrix Matrix Multiplication

In [ ]:
def mat_mat_multiplication(mata, matb):
    assert mata.shape