# Array Creation
Array's  can be created in multiple ways in NumPy

In [4]:
%pip install numpy

  Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/72/b2/02770e60c4e2f7e158d923ab0dea4e9f146a2dbf267fec6d8dc61d475689/numpy-1.25.2-cp311-cp311-win_amd64.whl.metadata
Using cached numpy-1.25.2-cp311-cp311-win_amd64.whl (15.5 MB)
Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np # import numpy into current session

In [4]:
# Array using python list
l1 = [1,2,3,4,5,6,7,8,9]
np.array(l1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.zeros(10) # array of zeros parameter will represent no of elements in array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
# array using np.ones function
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
# array usinf np.full
np.full(10, 20) # first arg represent no of elements second arg represent value to be filled in the array

array([20, 20, 20, 20, 20, 20, 20, 20, 20, 20])

In [36]:
np.arange(1,5) # array using arange function

array([1, 2, 3, 4])

In [13]:
np.array((2,5)) #array using python tuple

array([2, 5])

In [16]:
np.random.rand(10) # array using random function

array([0.52029093, 0.14996177, 0.04648363, 0.54638007, 0.23258999,
       0.31928237, 0.47397067, 0.11053376, 0.78116317, 0.35403551])

In [17]:
np.random.seed(10) # to retrive same random number everytime using the seed number
np.random.rand(5)

array([0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701])

In [19]:
np.linspace(10,20,11) # linspace function create linear number of elements between the range of numbers 
                      # arg1 represenet start of range arg2 end of range arg3 represent number of elements to be generated linearly between the range

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20.])

# Multi Dimensional Array's 
#### using NumPy we can create N-dimension array's

In [39]:
l2 = [[1,2,3],[3,5,6]]
np.array(l2) # 2-D array using python list

array([[1, 2, 3],
       [3, 5, 6]])

In [41]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [42]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

# Array Access Operations
##### NumPy array can be accessed similar to python lists

In [25]:
a = np.random.rand(10)
a

array([0.0768555 , 0.85304299, 0.43998746, 0.12195415, 0.73173462,
       0.13878247, 0.76688005, 0.83198977, 0.30977806, 0.59758229])

In [28]:
a[0] # access 1st element; index start from zero same as python list

0.07685550174624711

In [30]:
a[-1] # access last element of numpy array

0.5975822902915008

In [32]:
a[0:4] # access range of elements last element not included

array([0.0768555 , 0.85304299, 0.43998746, 0.12195415])

In [33]:
a[-4:-1] # range of ele can also be accessed using negative indexes

array([0.76688005, 0.83198977, 0.30977806])

In [43]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
b[0,1] # access first element in 2D array

2

In [46]:
b[0,] # access single row

array([1, 2, 3])

In [49]:
b[:,0] # access single column

array([1, 4, 7])

In [51]:
b[:2,:2] # access part of 2D array

array([[1, 2],
       [4, 5]])

# Summarization Operations
#### Ex: sum, min, max, mean, std

In [53]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [55]:
a.mean() # mean of array

9.5

In [56]:
a.min() # min value of array

0

In [57]:
a.max() #max value of array

19

In [60]:
a.sum() #sum of array

190

In [62]:
len(a) # length of array

20

In [64]:
a.std() # standard deviation

5.766281297335398

# Element wise operations

In [68]:
x = np.arange(1,5)
y = np.arange(2,6)
x,y

(array([1, 2, 3, 4]), array([2, 3, 4, 5]))

In [69]:
x>y

array([False, False, False, False])

In [70]:
y>x

array([ True,  True,  True,  True])

In [71]:
x*y

array([ 2,  6, 12, 20])

In [73]:
(x*y)/1.5

array([ 1.33333333,  4.        ,  8.        , 13.33333333])

In [75]:
x/y

array([0.5       , 0.66666667, 0.75      , 0.8       ])

In [76]:
x**y

array([   1,    8,   81, 1024])